"""
Scaffold a new Django collector app: models, services, BaseCollectorCommand + AbstractCollector,
tests package, initial migration file, and a YAML schedule snippet template.
"""

from __future__ import annotations

import re
import textwrap
from pathlib import Path
from typing import Any

from django.apps import apps
from django.conf import settings
from django.core.management import call_command
from django.core.management.base import BaseCommand, CommandError

from core.management.collector_registry import register_collector_project_files


_APP_LABEL_RE = re.compile(r"^[a-z][a-z0-9_]*$")

# Names that must not be used as app labels (stdlib / Django / project layout).
_RESERVED = frozenset(
    {
        "admin",
        "auth",
        "config",
        "contenttypes",
        "core",
        "django",
        "environ",
        "manage",
        "messages",
        "migrations",
        "sessions",
        "settings",
        "staticfiles",
        "test",
        "tests",
        "urls",
        "wsgi",
    }
)


def _label_to_pascal(app_label: str) -> str:
    return "".join(part.capitalize() for part in app_label.split("_"))


def _verbose_name(app_label: str) -> str:
    return app_label.replace("_", " ").title()


def _schedule_snippet(app_label: str) -> str:
    cmd = f"run_{app_label}"
    return textwrap.dedent(
        f"""\
        # Paste under an existing group in config/boost_collector_schedule.yaml, or add a new group.
        # Example task (see docs/Workflow.md for schedule types and args):
        #
        #   - command: {cmd}
        #     schedule: daily
        #
        # Other schedule keys: weekly (with "on" or day_of_week), monthly, on_release, interval (with minutes).
        """
    )


def _models_py(app_label: str, pascal: str) -> str:
    return textwrap.dedent(
        f'''\
        """Customize: model fields for your domain. This stub proves migrations + ORM wiring."""

        from django.db import models


        class {pascal}RunState(models.Model):
            """One row per logical source key; stub for incremental or heartbeat-style state."""

            # CUSTOMIZE: replace source_key semantics (e.g. workspace id, channel id).
            source_key = models.CharField(max_length=128, unique=True, db_index=True)
            run_count = models.PositiveIntegerField(default=0)
            updated_at = models.DateTimeField(auto_now=True)

            class Meta:
                ordering = ["source_key"]
        '''
    )


def _services_py(app_label: str, pascal: str) -> str:
    return textwrap.dedent(
        f'''\
        """All creates/updates/deletes for {app_label} models must go through this module.

        See CONTRIBUTING.md (service layer). Call these functions from collectors and
        management commands instead of using Model.objects.* directly outside tests.
        """

        from __future__ import annotations

        from django.db import transaction

        from {app_label}.models import {pascal}RunState


        @transaction.atomic
        def record_run(*, source_key: str) -> tuple[{pascal}RunState, bool]:
            """Increment run_count for source_key, creating the row if missing."""
            if not source_key or not source_key.strip():
                raise ValueError("source_key must not be empty")
            key = source_key.strip()
            obj, created = {pascal}RunState.objects.select_for_update().get_or_create(
                source_key=key,
                defaults={{"run_count": 0}},
            )
            obj.run_count += 1
            obj.save(update_fields=["run_count", "updated_at"])
            return obj, created
        '''
    )


def _initial_migration_py(app_label: str, pascal: str) -> str:
    model = f"{pascal}RunState"
    return textwrap.dedent(
        f"""\
        # Generated by startcollector — matches models.{model}

        from django.db import migrations, models


        class Migration(migrations.Migration):

            initial = True

            dependencies = []

            operations = [
                migrations.CreateModel(
                    name="{model}",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "source_key",
                            models.CharField(db_index=True, max_length=128, unique=True),
                        ),
                        ("run_count", models.PositiveIntegerField(default=0)),
                        ("updated_at", models.DateTimeField(auto_now=True)),
                    ],
                    options={{
                        "ordering": ["source_key"],
                    }},
                ),
            ]
        """
    )


def _run_command_py(app_label: str, pascal: str) -> str:
    return textwrap.dedent(
        f'''\
        """Management command: run_{app_label}"""

        from __future__ import annotations

        import logging
        from typing import Any

        from core.collectors import AbstractCollector, BaseCollectorCommand, GenericTrackerResult

        import {app_label}.services as services

        logger = logging.getLogger(__name__)


        class {pascal}Collector(AbstractCollector):
            """Collector stub — replace collect() orchestration with real work."""

            def __init__(self, *, stdout: Any, style: Any, source_key: str = "default") -> None:
                self.stdout = stdout
                self.style = style
                self.source_key = source_key

            @property
            def name(self) -> str:
                return "{app_label}"

            def validate_config(self) -> None:
                if not self.source_key or not self.source_key.strip():
                    raise ValueError("source_key must not be empty")

            def collect(self) -> GenericTrackerResult:
                logger.info("run_{app_label}: starting")
                _, created = services.record_run(source_key=self.source_key.strip())
                self.stdout.write(
                    self.style.SUCCESS(
                        "{app_label} completed (stub); created=%s" % (created,)
                    )
                )
                logger.info("run_{app_label}: finished successfully")
                return GenericTrackerResult.ok(runs=1)


        class Command(BaseCollectorCommand):
            help = "Run the {app_label} collector (stub)."

            def get_collector(self, **_options: Any) -> AbstractCollector:
                return {pascal}Collector(stdout=self.stdout, style=self.style)
        '''
    )


def _apps_py(app_label: str, pascal: str, verbose: str) -> str:
    return textwrap.dedent(
        f"""\
        from django.apps import AppConfig


        class {pascal}Config(AppConfig):
            default_auto_field = "django.db.models.BigAutoField"
            name = "{app_label}"
            verbose_name = "{verbose}"
        """
    )


def _test_run_command_py(app_label: str, pascal: str) -> str:
    return textwrap.dedent(
        f'''\
        """Smoke test for run_{app_label}."""

        from io import StringIO

        import pytest
        from django.core.management import call_command


        @pytest.mark.django_db
        def test_run_{app_label}_writes_success():
            out = StringIO()
            call_command("run_{app_label}", stdout=out, verbosity=0)
            assert "completed" in out.getvalue().lower()
        '''
    )


class Command(BaseCommand):
    help = (
        "Create a new Django collector app with AbstractCollector + BaseCollectorCommand, "
        "services stub, models, tests, migrations, and schedule_snippet.yaml."
    )

    def add_arguments(self, parser: Any) -> None:
        parser.add_argument(
            "app_label",
            help="Django app package name (snake_case), e.g. my_platform",
        )
        parser.add_argument(
            "--path",
            default=".",
            help="Directory in which to create the app folder (default: current working directory).",
        )
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Print planned paths and YAML snippet; do not write files.",
        )
        parser.add_argument(
            "--no-register",
            action="store_true",
            help="Do not update project config files or run makemigrations (even at repo root).",
        )

    def handle(self, *args: Any, **options: Any) -> None:
        app_label: str = options["app_label"]
        base = Path(options["path"]).resolve()
        dry_run: bool = options["dry_run"]
        no_register: bool = options["no_register"]

        self._validate_app_label(app_label, base)

        app_dir = base / app_label
        pascal = _label_to_pascal(app_label)
        verbose = _verbose_name(app_label)
        snippet = _schedule_snippet(app_label)
        repo_root = Path(settings.BASE_DIR).resolve()
        should_register = (
            not no_register and base.resolve() == repo_root
        )

        if dry_run:
            self.stdout.write(
                self.style.NOTICE("Dry run — no files will be written.\n")
            )
            self.stdout.write(f"App directory: {app_dir}\n")
            self.stdout.write(
                "Files: apps.py, models.py, services.py, admin.py, views.py, "
                f"management/commands/run_{app_label}.py, "
                f"tests/test_run_{app_label}_command.py, "
                "schedule_snippet.yaml, migrations/0001_initial.py\n"
            )
            self.stdout.write("\n--- schedule_snippet.yaml (preview) ---\n")
            self.stdout.write(snippet)
            if should_register:
                self.stdout.write("\n--- project registration (preview) ---\n")
                for line in register_collector_project_files(
                    repo_root, app_label, dry_run=True
                ):
                    self.stdout.write(f"  {line}\n")
                self.stdout.write(
                    f"  Would run: python manage.py makemigrations {app_label}\n"
                )
            self.stdout.write("\n--- next steps ---\n")
            self._print_next_steps(app_label, registered=should_register)
            return

        app_dir.mkdir(parents=True, exist_ok=False)
        (app_dir / "__init__.py").write_text("", encoding="utf-8")
        (app_dir / "admin.py").write_text(
            textwrap.dedent(
                """\
                \"\"\"Django admin for this app — register ModelAdmin subclasses when needed.\"\"\"
                """
            ),
            encoding="utf-8",
        )
        (app_dir / "views.py").write_text(
            textwrap.dedent(
                """\
                # Create your views here.
                """
            ),
            encoding="utf-8",
        )
        mig_init = app_dir / "migrations" / "__init__.py"
        mig_init.parent.mkdir(parents=True, exist_ok=True)
        mig_init.write_text("", encoding="utf-8")

        tests_dir = app_dir / "tests"
        tests_dir.mkdir(exist_ok=True)
        (tests_dir / "__init__.py").write_text("", encoding="utf-8")
        (tests_dir / f"test_run_{app_label}_command.py").write_text(
            _test_run_command_py(app_label, pascal),
            encoding="utf-8",
        )

        (app_dir / "models.py").write_text(
            _models_py(app_label, pascal), encoding="utf-8"
        )
        (app_dir / "services.py").write_text(
            _services_py(app_label, pascal), encoding="utf-8"
        )
        (app_dir / "apps.py").write_text(
            _apps_py(app_label, pascal, verbose), encoding="utf-8"
        )

        mgmt = app_dir / "management"
        mgmt.mkdir(exist_ok=True)
        (mgmt / "__init__.py").write_text("", encoding="utf-8")
        cmds = mgmt / "commands"
        cmds.mkdir(exist_ok=True)
        (cmds / "__init__.py").write_text("", encoding="utf-8")
        (cmds / f"run_{app_label}.py").write_text(
            _run_command_py(app_label, pascal),
            encoding="utf-8",
        )

        (app_dir / "schedule_snippet.yaml").write_text(snippet, encoding="utf-8")

        mig_dir = app_dir / "migrations"
        (mig_dir / "0001_initial.py").write_text(
            _initial_migration_py(app_label, pascal),
            encoding="utf-8",
        )

        self.stdout.write(self.style.SUCCESS(f"Created collector app at {app_dir}\n"))
        self.stdout.write("\n--- schedule_snippet.yaml ---\n")
        self.stdout.write(snippet)
        self.stdout.write("\n")

        registered = False
        if should_register:
            self.stdout.write("--- project registration ---\n")
            for line in register_collector_project_files(
                repo_root, app_label, dry_run=False
            ):
                self.stdout.write(f"  {line}\n")
            call_command("makemigrations", app_label, verbosity=1)
            self.stdout.write(
                f"  Ran: python manage.py makemigrations {app_label}\n"
            )
            registered = True

        self._print_next_steps(app_label, registered=registered)

    def _validate_app_label(self, app_label: str, base: Path) -> None:
        if not _APP_LABEL_RE.match(app_label):
            raise CommandError(
                "app_label must match ^[a-z][a-z0-9_]*$ (lowercase start, letters, digits, underscore)."
            )
        if app_label in _RESERVED:
            raise CommandError(f'"{app_label}" is reserved; choose another app label.')
        installed_labels = {cfg.label for cfg in apps.get_app_configs()}
        if app_label in installed_labels:
            raise CommandError(
                f'App "{app_label}" is already in INSTALLED_APPS. Remove it or pick a new name.'
            )
        candidate = base / app_label
        if candidate.exists():
            raise CommandError(f"Path already exists: {candidate}")

    def _print_next_steps(self, app_label: str, *, registered: bool) -> None:
        if registered:
            self.stdout.write(
                textwrap.dedent(
                    f"""\
                    Next steps:
                      1. Review the commented schedule block in config/boost_collector_schedule.yaml — move it under the right groups.<name>.tasks, uncomment, then set enabled: true when production-ready.
                      2. Run: python manage.py migrate
                      3. Customize the stub row for "{app_label}" in docs/cross-app-dependencies.md (expand §1–§3 if you add cross-app imports or FKs).
                      4. Implement real domain logic in models.py, services.py, and collect().
                      5. After adding public service functions, run: python scripts/generate_service_docs.py
                      6. Run: uv run pytest and uv run pyright before opening a PR
                    """
                )
            )
            return

        self.stdout.write(
            textwrap.dedent(
                f"""\
                Next steps:
                  Registration skipped (app not created at repo root, or --no-register).
                  Re-run from the repository root without --path, or register manually:
                    1. Add "{app_label}" to INSTALLED_APPS in config/settings.py (keep alphabetical order).
                    2. Append schedule_snippet.yaml to config/boost_collector_schedule.yaml (see docs/Workflow.md).
                    3. Add "{app_label}" to root_packages in .importlinter.
                    4. Add a stub row for "{app_label}" in docs/cross-app-dependencies.md.
                    5. Run: python manage.py makemigrations {app_label} && python manage.py migrate
                    6. After adding real service functions, run: python scripts/generate_service_docs.py
                """
            )
        )
