from collections.abc import Callable, Mapping
from typing import Any, TypeVar, overload

_T = TypeVar("_T")

class Env:
    def __init__(self, **scheme: Any) -> None: ...
    @overload
    def __call__(
        self,
        var: str,
        *,
        cast: type[_T],
        default: _T,
        parse_default: bool = ...,
    ) -> _T: ...
    @overload
    def __call__(
        self,
        var: str,
        *,
        cast: type[_T],
        default: None = ...,
        parse_default: bool = ...,
    ) -> _T | None: ...
    @overload
    def __call__(
        self,
        var: str,
        *,
        cast: Callable[[Any], _T],
        default: _T,
        parse_default: bool = ...,
    ) -> _T: ...
    @overload
    def __call__(
        self,
        var: str,
        *,
        cast: Callable[[Any], _T],
        default: None = ...,
        parse_default: bool = ...,
    ) -> _T | None: ...
    @overload
    def __call__(
        self, var: str, *, default: None = ..., parse_default: bool = ...
    ) -> str | None: ...
    @overload
    def __call__(self, var: str, *, default: _T, parse_default: bool = ...) -> _T: ...
    @overload
    def __call__(self, var: str, default: _T, parse_default: bool = ...) -> _T: ...
    def __call__(
        self,
        var: str,
        cast: Any = ...,
        default: Any = ...,
        parse_default: bool = ...,
    ) -> Any: ...
    def bool(self, var: str, default: bool = ...) -> bool: ...
    def int(self, var: str, default: int = ...) -> int: ...
    def float(self, var: str, default: float = ...) -> float: ...
    def list(self, var: str, default: list[str] | None = ...) -> list[str]: ...
    def tuple(
        self, var: str, default: tuple[str, ...] | None = ...
    ) -> tuple[str, ...]: ...
    def json(
        self, var: str, default: Mapping[str, Any] | None = ...
    ) -> dict[str, Any]: ...
    def db(self, var: str, default: str = ...) -> dict[str, Any]: ...
    def url(self, var: str, default: str = ...) -> str: ...
    def path(self, var: str, default: str = ...) -> str: ...
    def email(self, var: str, default: str = ...) -> str: ...
    @classmethod
    def read_env(cls, env_file: str | None = None, **kwargs: Any) -> None: ...
