# Generated by startcollector — matches models.RedditSubmission and RedditComment

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RedditSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reddit_id",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("subreddit", models.CharField(db_index=True, max_length=128)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("author_id", models.CharField(blank=True, max_length=64)),
                ("title", models.CharField(max_length=1024)),
                ("selftext", models.TextField(blank=True)),
                ("selftext_html", models.TextField(blank=True)),
                ("url", models.URLField(max_length=1024)),
                ("permalink", models.CharField(max_length=512)),
                ("score", models.IntegerField(default=0)),
                ("num_comments", models.IntegerField(default=0)),
                ("created_utc", models.IntegerField(db_index=True)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Reddit submission",
                "verbose_name_plural": "Reddit submissions",
                "ordering": ["-created_utc", "reddit_id"],
            },
        ),
        migrations.CreateModel(
            name="RedditComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reddit_id",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("parent_id", models.CharField(blank=True, max_length=20)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("author_id", models.CharField(blank=True, max_length=64)),
                ("body", models.TextField(blank=True)),
                ("url", models.URLField(max_length=1024)),
                ("score", models.IntegerField(default=0)),
                ("created_utc", models.IntegerField(db_index=True)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="reddit_activity_tracker.redditsubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reddit comment",
                "verbose_name_plural": "Reddit comments",
                "ordering": ["created_utc", "reddit_id"],
            },
        ),
    ]
