class Error(Exception): ...

class DB:
    def __init__(self, path: str, *, create_if_missing: bool = ...) -> None: ...
    def get(self, key: bytes) -> bytes | None: ...
    def close(self) -> None: ...
    def iterator(self): ...
